### ISSUE TITLE
Clarify 'number' validation context

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Marketing-Cloud/htl-spec#20]
The number validation context should probably have been named 'long' as it only accepts whole numbers per the TCK. But IMHO this is not worth changing at this point for backwards compatibility reasons. I suggest just adding some clarifying language to the specification.

**Comment by raducotescu** [comment]
I think the `number` context should automatically validate both long and double values. HTL should not be used a validator, it should just make sure that the provided values cannot escape a well defined context.
