### ISSUE TITLE
Clarify where exactly Sightly Block Statements are supported

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/htl-spec#23]
At least within the starting and closing `<script>` it seems that Sightly Block Statements are just ignored. Please clarify in the specification where exactly Sightly Block Statements are supported.

**Comment by raducotescu** [comment]
The content of a `<script>` tag is Text, therefore block statements in `<script>` tags cannot be interpreted. For more details check https://www.w3.org/TR/html5/scripting-1.html#restrictions-for-contents-of-script-elements.
