### ISSUE TITLE
Not consistent behavior while using @query

### ISSUE THREAD

**Issue by etugarev** [Adobe-Marketing-Cloud/htl-spec#24]
Please consider the following example:

`<a href="${'###' @ context='attribute'}">`

The result is `<a href="###"></a>`

Now let's a add a query (assume `controller.model.query` is valid and evaluates to `?foo=bar`) 

`<a href="${'###' @ context='attribute', query=controller.model.query}">`

The result is a SightlyException & stack trace on  a page :

**The provided path does not represent a valid URI: ###**

So, i was able to break the page on author without being able any more to correct the invalid value  '###' which I _deliberately_ set in the component dialog.

To me it looks as not very consistent behaviour, would it be maybe better to return `###?foo=bar` in second case or return empty string in both cases?

**Comment by WillBro** [comment]
@etugarev I'm curious what happens when you use context='uri' rather than attribute?

**Comment by etugarev** [comment]
@WillBro Unfortunately exception getting thrown even before context is getting applied:
<pre><a href="http://grepcode.com/file/repo1.maven.org/maven2/org.apache.sling/org.apache.sling.scripting.sightly/1.0.2/org/apache/sling/scripting/sightly/impl/utils/PathInfo.java#60">60</a>  <font color="#7f0055"><b>try</b></font> {<br/><a href="http://grepcode.com/file/repo1.maven.org/maven2/org.apache.sling/org.apache.sling.scripting.sightly/1.0.2/org/apache/sling/scripting/sightly/impl/utils/PathInfo.java#61">61</a>      <a href="http://grepcode.com/file/repo1.maven.org/maven2/org.apache.sling/org.apache.sling.scripting.sightly/1.0.2/org/apache/sling/scripting/sightly/impl/utils/PathInfo.java#PathInfo.0uri" title="URI uri" class="hidden">uri</a> = <font color="#7f0055"><b>new</b></font> <a href="http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b27/java/net/URI.java#URI" title="java.net.URI">URI</a>(path);<br/><a href="http://grepcode.com/file/repo1.maven.org/maven2/org.apache.sling/org.apache.sling.scripting.sightly/1.0.2/org/apache/sling/scripting/sightly/impl/utils/PathInfo.java#62">62</a>  } <font color="#7f0055"><b>catch</b></font> (<a href="http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b27/java/net/URISyntaxException.java#URISyntaxException" title="java.net.URISyntaxException">URISyntaxException</a> e) {<br/><a href="http://grepcode.com/file/repo1.maven.org/maven2/org.apache.sling/org.apache.sling.scripting.sightly/1.0.2/org/apache/sling/scripting/sightly/impl/utils/PathInfo.java#63">63</a>      <font color="#7f0055"><b>throw</b></font> <font color="#7f0055"><b>new</b></font> <a href="http://grepcode.com/file/repo1.maven.org/maven2/org.apache.sling/org.apache.sling.scripting.sightly/1.0.2/org/apache/sling/scripting/sightly/SightlyException.java#SightlyException" title="org.apache.sling.scripting.sightly.SightlyException">SightlyException</a>(<font color="#2a00ff">"The provided path does not represent a valid URI: "</font> + path);<br/><a href="http://grepcode.com/file/repo1.maven.org/maven2/org.apache.sling/org.apache.sling.scripting.sightly/1.0.2/org/apache/sling/scripting/sightly/impl/utils/PathInfo.java#64">64</a>  }<br/></pre>

**Comment by raducotescu** [comment]
@etugarev, the problem you're describing is:

1. related to the implementation, and not to the specification
2. invalid, since you're indeed not using a valid URI to which you want to append a query
