### ISSUE TITLE
IE Conditional comments wouldn't be working

### ISSUE THREAD

**Issue by drfits** [Adobe-Marketing-Cloud/htl-spec#29]
Not sure about importance of this issue but anyway code below couldn't be parsed with HTL correctly:
```
<!--[if lt IE 9]>
    <sly data-sly-call="${clientlib.js @ categories='html5shiv-3.7.0'}"/>
<![endif]-->
```
Output:
```
<!--[if lt IE 9]>
    <sly data-sly-call=""></sly>
<![endif]-->
```

**Comment by vladbailescu** [comment]
As per the [specification](https://github.com/Adobe-Marketing-Cloud/htl-spec/blob/master/SPECIFICATION.md#119-comments):

> HTL expressions inside HTML comments are evaluated, but not block statements

**Comment by paul-bjorkstrand** [comment]
This is an unfortunate problem caused by the spec. I agree with the spec, but it can be a pain to implement this.

@drfits, my workaround typically means calling the granite clientlib use object directly (works on 6.1, probably on 6.2 as well):

```html
<template data-sly-template.conditionalClientlibForIE="${@ mode='css, js, or omitted for both', categories='categories to be included'}", lteVersion='the maximum version of IE this clientlib should be included for'
    data-sly-use.clientlib="${libs.granite.sightly.templates.ClientLibUseObject @ categories=categories, mode=mode}">
    <!--[if lte IE ${lteVersion}]>
        ${clientlib.include @ context='unsafe'}
    <![endif]-->
</template>
```
