### ISSUE TITLE
suffixSelectors and suffixExtention URI manipulation support

### ISSUE THREAD

**Issue by StoicPerlman** [Adobe-Marketing-Cloud/htl-spec#32]
I propose the ability to treat suffixes as their own URI (limited to selectors and extensions). A suffix can point to another page and it would be nice to be able to easily modify selectors/extensions for that page.

Currently to get this functionality I have to spit off my suffix and manipulate it then appends it onto the base url. (Or do it in Java with the suffix as a new PathInfo object and append that)

`// here request.pathInfo already has suffix stripped off and copied in hostPath`
`<a href="${request.pathInfo @ selectors='host'}${requestUtil.attributes['hostPath'] @ selectors=item.selector}">${item.title}</a>`

 It would be great to have expression options to do this directly like this:

`<a href="${request.pathInfo @ selectors='host',  suffixSelectors=item.selector}">${item.title}</a>` 

Maybe this should be a separate issue but I will mention it here. It would also be great to be able to do request.pathInfo.suffix, request.pathInfo.path, etc. in htl.

**Comment by raducotescu** [comment]
@StoicPerlman, you seem to be referring to the Servlet API, judging by the `request.pathInfo` calls. However, the [HttpServletRequest#getPathInfo](http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getPathInfo--) method returns a `String`. If you need the `RequestPathInfo` Sling API object, then your calls should look like: `request.requestPathInfo`.

Regarding suffix manipulation, the suffix can be any string, not necessarily a path, therefore URI manipulation for that string doesn't really make sense.
