### ISSUE TITLE
Allow i18n to be turned on/off by a boolean expression

### ISSUE THREAD

**Issue by paul-bjorkstrand** [Adobe-Marketing-Cloud/htl-spec#38]
Pretty self explanatory, allow the construct `${'some text' @ i18n=someCondition}`, defaulting to `true` if `=someCondition` is not present. This would treat `${'some text' @ i18n}` as `${'some text' @ i18n=true}`

I have a few situations in a legacy application migration that would benefit from this ability.

**Comment by raducotescu** [comment]
If you need to conditionally translate expression outputs, then please use {{data-sly-test}}. I know that for your use case the code would become uglier, but this doesn't warrant for a change in the specification.
