### ISSUE TITLE
Rendering of ${['']} in an attribute inconsistent with the spec

### ISSUE THREAD

**Issue by toniedzwiedz** [Adobe-Marketing-Cloud/htl-spec#39]
According to [the specification](https://github.com/Adobe-Marketing-Cloud/htl-spec/blob/master/SPECIFICATION.md#2231-detailed-examples), attributes containing an array with just an empty string should be rendered with an empty value:

>     
>     <div title="${['']}"></div>
>     
>     <div title=""></div>

However, when I try the same code on my AEM instance, I get the following output:

    <div></div>

I'm using AEM 6.2 and the following bundles:
- Apache Sling Scripting Sightly Engineorg.apache.sling.scripting.sightly	1.0.18
- Apache Sling Scripting Sightly JavaScript Use Providerorg.apache.sling.scripting.sightly.js.provider	1.0.10	sling
- Apache Sling Scripting Sightly Models Use Providerorg.apache.sling.scripting.sightly.models.provider	1.0.0
- Adobe Experience Manager Sightly Extensioncom.adobe.cq.sightly.cq-wcm-sightly-extension	1.3.8
- Adobe Granite Sightly Template Engine (compatibility)io.sightly.bundle	1.1.72

Is this an error in the specification or is this a bug in my specific version and one of the bundles requires an update?

**Comment by vladbailescu** [comment]
This seems to be an implementation bug. I will update the HTL TCK with a relevant test, file an issue in SLING and submit a patch.

**Comment by toniedzwiedz** [comment]
Thanks @vladbailescu

**Comment by mehtarachna** [comment]
Hi, is this issue resolved? seems to be not working for me on 6.4.5

**Comment by raducotescu** [comment]
@mehtarachna, if you have any implementation issues please use the official support channels for reporting them. For AEM, the instructions are available at https://helpx.adobe.com/experience-manager/kb/accessing-aem-support-portal.html.

**Comment by szymon-owczarzak** [comment]
8 years has past since and the problem is still present.
For example:
```html
<div 
  foo="bar"
  test-1=""
  test-2="${''}"
  test-3="${['']}"
  data-sly-attribute.test-4=""
  data-sly-attribute.test-5="${''}"
  data-sly-attribute.test-6="${['']}">
    tests
</div>
```
evaluates to:
```html
<div foo="bar" test-1="">
tests
</div>
```
✅  however there is a workaround for a11y purposes:

```html
<img data-sly-attribute.alt="${model.altText || true}">
```
will produce:

```html
<img alt>
```

**Comment by garthbongers** [comment]
> ✅ however there is a workaround for a11y purposes:
> 
> `<img data-sly-attribute.alt="${model.altText || true}">`
> will produce:
> 
> `<img alt>`

From what I gather this isn't equivalent to `<img alt="">`. Screen readers may interpret this as a missing value (as opposed to an empty string) and then still fallback to the filename.

Until this bug gets fixed, it looks like an okay (but not as good) workaround is to apply [the `role="presentation"` attribute](https://www.w3.org/WAI/tutorials/images/decorative/#example-1-image-used-as-part-of-page-design).

```
alt="${image.alt || ''}"
role="${!image.alt && 'presentation' || ''}"
```

It would be great to get this bug fixed if possible.

**Comment by dbkup** [comment]
The only way to get this correct for a11y purposes `(alt="")` is by having two `<img>` elements wrapped in data-sly-test:
```
<sly data-sly-test=${properties.altText}>
  <img alt=${properties.altText}" src"..."/>
</sly>
<sly data-sly-test=${!properties.altText}>
  <img alt="" src"..."/>
</sly>
```
I came back to find an alternative, and found the spec is misleading. At least we should correct the spec if this feature is not going to be implemented.

**Comment by garthbongers** [comment]
I've been resisting creating this redundancy, but if more in-depth a11y testing reveals that changing the `role` of the `<img>` isn't sufficient (and we already know it's not really comparable to the correct use of `alt=""`), then repeating the tag with the correct form of the `alt` attribute will have to do!
