### ISSUE TITLE
data-sly-text not rendering HTML

### ISSUE THREAD

**Issue by leoxy520** [Adobe-Marketing-Cloud/htl-spec#40]
We are upgrading to AEM 6.3 and have noticed this problem. 

`<div data-sly-text=${properties.desc @ context='html'}></div> 
`

is outputting the HTML escaped. 

If I do :

`<div>${properties.desc @ context='html'}</div>
`

it is working as intended. 

Is this a new feature for 6.3? If there is a way to fix this, please let me know as this requires quite some refactoring effort to fix.

Thanks.

**Comment by vladbailescu** [comment]
This is most probably a bug in the implementation. As per the [specification](https://github.com/Adobe-Marketing-Cloud/htl-spec/blob/master/SPECIFICATION.md#222-text), the expected behavior should be:

> The content of the data-sly-text attribute is automatically XSS-protected with the text context, unless stated otherwise

**Comment by raducotescu** [comment]
@leoxy520, I've opened https://issues.apache.org/jira/browse/SLING-6866. Please provide more details there (e.g. bundle version for sightly / htl), since this is an implementation bug, like @vladbailescu mentioned.
