### ISSUE TITLE
Clarify how objects in expressions are evaluated

### ISSUE THREAD

**Issue by santiagozky** [Adobe-Marketing-Cloud/htl-spec#41]
From the HTL expression it is not clear to me what should be the proper output for
`${resource}` where resource is a simple POJO.

My expectation would be that it follows the JSP EL language rules which indicates that the toString() method is called in such cases. [0]

The apache implementation currently seems to print nothing, which is counterintuitive to me.

Could you please clarify how this should work?

0- section 1.2.1.1 http://download.oracle.com/otn-pub/jcp/jsp-2.1-fr-spec-oth-JSpec/jsp-2_1-fr-spec-el.pdf?AuthParam=1499856940_8baf9732bece797be47d8353c416c0d2

**Comment by raducotescu** [comment]
HTL understands three data types: Strings, Numbers and Booleans. Everything else is casted to one of these data types, depending on the context - see [1].

Forcing and implementation (in this case Java) to perform String casts automatically might introduce backwards incompatible changes for some HTL scripts.

If you feel that this issue deserves a more thorough discussion please feel free to reopen it.

[1] - https://github.com/Adobe-Marketing-Cloud/htl-spec/blob/1.3.1/SPECIFICATION.md#115-casting
