### ISSUE TITLE
Some examples from the URI manipulation section are not correct

### ISSUE THREAD

**Issue by raducotescu** [Adobe-Marketing-Cloud/htl-spec#43]
The following examples are incorrect:

1. `example.com` is not a valid domain in this context:
```
${'example.com/path/page.html' @ scheme='http'}
<!-- outputs: http://example.com/path/page.html -->
```
2. selectors should not be merged, but rather appended
```
${'path/page.woo.foo.html' @ addSelectors='foo.bar'}
<!-- outputs: path/page.woo.foo.bar.html -->

${'path/page.woo.foo.html' @ addSelectors=['foo', 'bar']}
<!-- outputs: path/page.woo.foo.bar.html -->
```

**Comment by NicolaExp9999** [comment]
Excuse me, I have a question.
Your correct example:
"${“path/page.woo.foo.html” @ addSelectors=[“foo”, “bar”]}
" – is this possible if the selectors are treated as sets?

As we are running the test with duplicate selectors and the engine is removing the duplicates


https://github.com/apache/sling-org-apache-sling-scripting-sightly/blob/f7f73e2feefb39a4496a85a093fe834aca92fb01/src/main/java/org/apache/sling/scripting/sightly/impl/engine/extension/ResourceRuntimeExtension.java#L176
