### ISSUE TITLE
Remove octal escape sequences from grammar

### ISSUE THREAD

**Issue by karollewandowski** [Adobe-Marketing-Cloud/htl-spec#45]
Grammar includes octal escape sequences in string definition, but Sling HTL implementation omits  it. Is it going to be implemented in future? I don't know whether I should support it in IntelliJ plugin I'm working on.
If it should be removed and you don't mind if I do it and create PR, please let me know.

**Comment by raducotescu** [comment]
@karollewandowski, I think the octal escape should be removed from the grammar.
