### ISSUE TITLE
Should the language spec include specific treatment on implicit unwrapping of optional values for backend languages that support them?

### ISSUE THREAD

**Issue by adamcin** [Adobe-Marketing-Cloud/htl-spec#47]
We are encouraging the use of Java 8 Streams in our service and model code, which had led to prolific use of java.util.Optional<T> return types for many model getters and service methods, which are treated opaquely as non-null runtime Objects if accessed in HTL. From my personal perspective, though, java Optional values should be treated as a special case, just like `null` or `Map`:

1. `Optional.empty()` in the context of a single value is implicitly unwrapped to null and treated the same way, i.e. `toBoolean(value)` -> `false`, `toString(value)` -> `''`, toCollection -> `[]`.
2. `Optional.of(foo)` in the context of a single value is implicitly unwrapped to `foo` and subjected to the same rules described above, and with subsequent property expressions applied only to `foo` and not to the Optional wrapper.

My question though is whether such behavior should be left up to the backend languages to define, or if this is something that needs to be explicitly defined by the HTL spec.

**Comment by raducotescu** [comment]
This should be treated by the implementations the way they see it fit. HTL, except for the Use-API, tries to stay away from language-specific details. Please let me know if this answers your question.

If you need support for `Optional` in the reference implementation, the best way is to open a SLING issues at https://issues.apache.org/jira/projects/SLING.
