### ISSUE TITLE
Fix for @extension for external link without page extension

### ISSUE THREAD

**Issue by pony-soeung** [Adobe-Marketing-Cloud/htl-spec#48]
Hello,
For : ${'https://www.adobe.com/fr/' @ extension ='html'}
it will generate :  https://www.adobe.com/fr/.html
should be : https://www.adobe.com/fr/

**Comment by vladbailescu** [comment]
You will need to report this issue to https://issues.apache.org/jira/projects/SLING, that's where the implementation of HTL is.
