### ISSUE TITLE
Add Sightly context for JSON inline data

### ISSUE THREAD

**Issue by vladbailescu** [Adobe-Marketing-Cloud/htl-spec#5]
I propose to add a new context for inline JSON data. This will encode HTML entities in order to prevent XSS attacks.

At the moment the only way to add inline JSON data is by using `context="unsafe"`. This is both semantically incorrect and dangerous (no XSS protection out-of-the-box).

**Comment by kwin** [comment]
@vladbailescu @raducotescu Can you please explain why you don't want to add this context to the HTL spec? I think closing an issue without putting any reasoning in it is a bit rude.

**Comment by raducotescu** [comment]
Not when you close your own issue. But I'll let @vladbailescu to explain the reasons to you. :)

>  I think closing an issue without putting any reasoning in it is a bit rude.

**Comment by vladbailescu** [comment]
@kwin Sorry if this came out as rude, that was definitely not the intention. Since the issue was opened and had no other comments from the community I thought it does not require an explanation. Thank you for bringing this up and here's what happened:

We re-evaluated this idea and dropped it because we felt we were forcing too much outside logic into HTL as the JSON would have to be parsed, validated and cleaned before outputting.

Also, we think there are better tools for this and would like to not encourage inline JSON since there are better ways to get a hold of the data: asynchronous loading and data attributes.

As always, we encourage anyone in the community to step up and voice their concerns/wishes and are happy to discuss further improvements when presented with solid arguments.

**Comment by vladbailescu** [comment]
Same goes for https://github.com/Adobe-Marketing-Cloud/htl-spec/issues/6

**Comment by kwin** [comment]
Basically there were 5 thumbs up on that issue, so obviously the community had the same issue :-). Thanks for elaborating on your thoughts. 

Let me give a concrete use case: We want to embed JSON-LD in our HTML pages (https://www.w3.org/TR/json-ld/#embedding-json-ld-in-html-documents). JSON-LD is used for enriching pages with semantical metadata in the form of JSON. Google only supports JSON-LD if directly embedded in the html (https://developers.google.com/search/docs/guides/intro-structured-data) but not if referenced through a dedicated URL. That means we also want to output that JSON-LD data within the body or head of an html page which is purely rendered with HTL components.

**Comment by dbkup** [comment]
Came here for the exact same use-case mentioned by @kwin namely supporting JSON-LD. I believe it's something where we could benefit with the HTL context for JSON to provide a built in feature instead of rolling out specific implementations.

**Comment by ruchimishra** [comment]
Exactly the same use case as above. I was just implementing JSON-LD and realized that we have to use the context = unsafe

**Comment by sabyamon** [comment]
Same situation. Looks like embedding JSON-LD to make google happy has become the "thing" and `context = unsafe` is the only way to go?

**Comment by toniedzwiedz** [comment]
Using `context="unsafe"` becomes somewhat troublesome when deploying via Cloud Manager. This rightly flagged by SonarQube during static code analysis but, as far as I'm aware, it's not possible to mark it as a _won't fix_ (which I would be inclined to do in this specific case if I had access to the SonarQube instance). In some cases, it's possible to use a data attribute as opposed to a script element to render a JSON document for front-end access but it's not so with the JSON-LD format mentioned by @kwin.

**Comment by simontunnat** [comment]
Has there been any progress on this matter? :)

**Comment by kwin** [comment]
What about just a context for JSON string values? That should be much smaller (and should be quite close to the existing context `scriptString` (https://github.com/apache/sling-org-apache-sling-scripting-sightly/blob/192d953514e6e579428cda157a7e83fc2a05cc01/src/main/java/org/apache/sling/scripting/sightly/impl/engine/extension/XSSRuntimeExtension.java#L126).
