### ISSUE TITLE
data-sly-include parameter

### ISSUE THREAD

**Issue by yunusadobe** [Adobe-Marketing-Cloud/htl-spec#51]
data-sly-include uses the property name **file** instead of **path** as documented in the https://helpx.adobe.com/experience-manager/htl/using/block-statements.html page.

Therefore, **file** should be renamed to **path** as in the provided documentation.

**Comment by raducotescu** [comment]
@yunusadobe, thank you for the report. `file` is the correct option. I'll have to talk to my colleagues to correct the example from https://helpx.adobe.com/experience-manager/htl/using/block-statements.html#include.
