### ISSUE TITLE
Attribute identifier for Unwrap block statement 

### ISSUE THREAD

**Issue by felipeS** [Adobe-Marketing-Cloud/htl-spec#52]
Why the Unwrap block statement `data-sly-unwrap` doesn't have an Attribute identifier so the result of the test can be used later on?

**Comment by raducotescu** [comment]
I guess we didn't consider it important, since if you have an `ifelse` construct you'd normally use `data-sly-test` with an identifier to store your expression's result.

Would this solution overcomplicate your markup?

**Comment by raducotescu** [comment]
Gave it a bit more thought and this enhancement should be seen as syntactic sugar 🍯.
