### ISSUE TITLE
Void elements and data-sly-test

### ISSUE THREAD

**Issue by karollewandowski** [Adobe-Marketing-Cloud/htl-spec#54]
_I'm not sure if it is HTL specification or rather implementation issue. Please tell me if issue should created in Sling project._

There is an issue with [HTML void elements](https://www.w3.org/TR/html5/syntax.html#void-elements). Eg.
```html
<link data-sly-test="${condition}" rel="canonical" href="http://example.com">
<!--  a lot of additional markup here -->
<!--  end of file -->
```
`<link>` element is void element and can be used without closing. Above markup leads to the bug, because `data-sly-test` will be applied to the end of file as there is no closing `link` tag. If it is expected behavior I think specification should include notice to close such elements to avoid bugs.

**Comment by paul-bjorkstrand** [comment]
I think this is an implementation bug, not necessarily a specification bug. The spec could be more clear about how to handle implicitly self closing tags, and force the implementation's hand, but that would really be its only influence.

Some time ago, I opened https://issues.apache.org/jira/browse/SLING-7549, but it has gotten zero traction.

Funny note: I made almost the same comment (in reverse) as your first couple sentences on my SLING ticket:

> Note: I was unsure if this should be something in the HTL spec or in the implementation. Since I found no reference in the specification regarding html5/xhtml/html4 compliance, I came here with my request instead. Please let me know if this is something that should be addressed at the specification level.

**Comment by raducotescu** [comment]
@karollewandowski, as noted by @paul-bjorkstrand this is an implementation bug, so keep your eyes on SLING-7549.
