### ISSUE TITLE
Not all supported operators are included in the grammar

### ISSUE THREAD

**Issue by lachlanmcdonald** [Adobe-Marketing-Cloud/htl-spec#58]
The grammar omits the operands listed under the "[Comparison Operators](https://github.com/Adobe-Marketing-Cloud/htl-spec/blob/master/SPECIFICATION.md#1142-comparison-operators)" heading.

```
operator = '&&'
         | '||' ;
```

Could perhaps become:

```
operator = '&&'
         | '||'
         | '<='
         | '<'
         | '>'
         | '=='
         | '!=' ;
```

**Comment by raducotescu** [comment]
Added the comparison operators in 8c0c409. See #53 for `&&` and `||`. See #56 for `in`.
