### ISSUE TITLE
Specification counter-intuitive on odd and even for data-sly-list and data-sly-repeat

### ISSUE THREAD

**Issue by lachlanmcdonald** [Adobe-Marketing-Cloud/htl-spec#59]
Perhaps this is intentional behaviour within the Sling, so excuse the issue if just a misunderstanding: 

The specification references that `itemList` will have the `odd` and `even` properties as:

> `odd`: `true` if index is odd;
> `even`: `true` if index is even;

With zero-based numbering, then the second item to be output by the loop will counter-intuitively be odd, not even, i.e.:

```js
0 % 2 === 0; // true
1 % 2 === 0; // false
2 % 2 === 0; // true
```

Perhaps the specification should replace `index` with `count` so that:

> `odd`: `true` if `count` is odd;
> `even`: `true` if `count` is even;

**Comment by raducotescu** [comment]
@lachlanmcdonald, you're absolutely right. There's a typo there. 😞
