### ISSUE TITLE
Clarification of template identifiers

### ISSUE THREAD

**Issue by lachlanmcdonald** [Adobe-Marketing-Cloud/htl-spec#66]
Hi,

I have a few questions regarding edge-cases for `data-sly-template` that I was hoping to have clarified:

**Can templates be called prior to declaration**

Would the following render `bar` or throw an error?

The spec states:

> The identifier set by the data-sly-template block element is global and available no matter if it's accessed before or after the template's definition

Which I assume also means that the template function is global?

```html
<div data-sly-call="${foo}"></div>
<template data-sly-template.foo>bar</template>
```

If templates are global, would the following return `bar`, `xyz` or throw an error?

```html
<div data-sly-call="${foo}"></div>
<template data-sly-template.foo>bar</template>
<template data-sly-template.foo>xyz</template>
```

**Can templates be referred to by a string**

Would the following return `foo` or throw an error?

```html
<div data-sly-call="${ true ? "foo" : "bar"  }"></div>
<template data-sly-template.foo>foo</template>
<template data-sly-template.bar>bar</template>
```

**Output of template identifier?**

What is output by `${foo}` in the snippet below?

```html
${foo}
<template data-sly-template.foo>bar</template>
${foo}
```

**Comment by tripodsan** [comment]
> Can templates be called prior to declaration

IMO, templates are effectively compiled into functions. most languages (java, javascript, c, c++) allow to call functions or methods out-of-order. also, the wording of the spec supports this. 
however, practically, it is nicer code if you declare the templates before they are used.

> Can templates be referred to by a string

yes. by any expression.

> Output of template identifier?

how about the name of the template? so just `foo` in your example ?

**Comment by lachlanmcdonald** [comment]
Excellent, thanks @tripodsan .

Does this mean that we'd expect:

```html
<template data-sly-template.foo>foo</template>
${foo == 'foo'}
```

To evaluate as `true`?
