### ISSUE TITLE
Support nested ternary

### ISSUE THREAD

**Issue by robotnewyork** [Adobe-Marketing-Cloud/htl-spec#68]
Nested ternary in HTL / Sightly causes error. 

<sly data-sly-test.myVar="${style == 'none' ? '' : style == 'image' ? imageSrc : backgroundColor}" />

**Comment by karollewandowski** [comment]
Nested ternary operators are allowed in grammar and work without any issues for me, eg.:
```
${'something' ? 'a' : ('1' ? 'x' : 'x')} // prints a
${'' ? 'a' : ('1' ? 'x' : 'x')} // prints x
```
Nested expressions have to be enclosed in parentheses. If it's not the case, then I think you should post snippet that does not work.

**Comment by robotnewyork** [comment]
Thanks, I did not realize nested expressions had to be enclosed in parenthesis. Closing issue.
